checkout source at http://code.google.com/p/newspaper-puzzles/source/checkout
setup eclipse to work with android projects (see http://developer.android.com/intl/zh-CN/guide/developing/eclipse-adt.html)
import project into eclipse
set project build target, currently using 1.6 for releases
